#!/bin/sh
# Rsync Backup Script
# https://github.com/oxhak/rsync-backup
# Backup Your Whole System Into A Folder.
# Maintains the rights and properties of files when copying.
# How to restore from this backup ? See HowToRestore file in this repos.
#
# Ox HaK
# https://oxhak.fr
# https://twitter.com/OxHaK
# https://keybase.io/oxhak

#Destination of the backup, ! do not put / at the end ! 
# ! do not miss to add an exclude to this destination in backup.lst ! - /backup/*
DESTINATION="/backup"

#Exclude file list, see backup.lst in this repos
EXCLUDE="backup.lst"

#Mount the hdd for destination backup
sudo mount /dev/sdb1 /backup;

#Do the backup
    sudo rsync -aAXvH --ignore-errors --numeric-ids --delete-excluded --progress --exclude-from=$EXCLUDE / $DESTINATION;
    
#Write the last backup into a file
    touch $DESTINATION/BACKUP;
    echo "Backup done at $(date +%d/%m/%Y) $(date +%Hh%M)." >> $DESTINATION/BACKUP;

sleep 1;
# umount the hdd for destination backup
sudo umount /dev/sdb1 &&

echo "---------------------------";
echo "Backup done!";
echo "---------------------------";
